version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=craftscan
      - MONGO_INITDB_ROOT_PASSWORD=craftscan
    ports:
      - 27017:27017

  populator:
    image: mongo
    restart: on-failure
    volumes:
      - ./populator/data:/data
    links:
      - mongodb
    command: mongoimport --host mongodb --authenticationDatabase admin --username craftscan --password craftscan --drop --db craftscan --collection ip2location --type csv --file "/data/IP2LOCATION-LITE-DB1.CSV" --fields ip_from,ip_to,country_code,country_name